FAKEDIR=../fake/
FITSDIR=../fits/
NSAMPLES=1000

.PHONY:
	fake \
	fakedehnen \
	fitfake \
	fitfakedehnen

fake:
	$(PYTHON) createFakeData.py \
	-o $(FAKEDIR)fake_simpledrift_noro_dwarf_vpec_sratio_hs.fits \
	--nvlos=201 --dfmodel=simplegaussiandrift \
	$(FITSDIR)all_simpledrift_noro_dwarf_vpec_sratio_hs.sav \
	--noro -m 15 --dwarf --fitvpec --fitsratio --fiths

fitfake:
	$(PYTHON) fitvc.py \
	-f $(FAKEDIR)fake_simpledrift_noro_dwarf_vpec_sratio_hs.fits \
	--dfmodel=simplegaussiandrift \
	$(FAKEDIR)all_simpledrift_noro_dwarf_vpec_sratio_hs.sav \
	--noro --dwarf --fitvpec --fitsratio --fiths
	$(PYTHON) fitvc.py \
	-f $(FAKEDIR)fake_simpledrift_noro_dwarf_vpec_sratio_hs.fits \
	--dfmodel=simplegaussiandrift \
	$(FAKEDIR)all_simpledrift_noro_dwarf_vpec_sratio_hs_$(NSAMPLES).sav \
	--mcsample --nsamples=$(NSAMPLES) \
	--init=$(FAKEDIR)all_simpledrift_noro_dwarf_vpec_sratio_hs.sav \
	--noro --dwarf --fitvpec --fitsratio --fiths

fakedehnen:
	$(PYTHON) createFakeData.py \
	-o $(FAKEDIR)fake_simpledrift-dehnen_noro_dwarf_vpec_sratio_hs.fits \
	--nvlos=201 --dfmodel=dehnen \
	$(FITSDIR)all_simpledrift_noro_dwarf_vpec_sratio_hs.sav \
	--noro -m 15 --dwarf --fitvpec --fitsratio --fiths

fitfakedehnen_hr3:
	$(PYTHON) fitvc.py \
	-f $(FAKEDIR)fake_simpledrift-dehnen_noro_dwarf_vpec_sratio_hs.fits \
	--dfmodel=simplegaussiandrift \
	$(FAKEDIR)all_simpledrift-dehnen_noro_dwarf_vpec_sratio_hs_hr3.sav \
	--noro --dwarf --fitvpec --fitsratio --fiths
	$(PYTHON) fitvc.py \
	-f $(FAKEDIR)fake_simpledrift-dehnen_noro_dwarf_vpec_sratio_hs.fits \
	--dfmodel=simplegaussiandrift \
	$(FAKEDIR)all_simpledrift-dehnen_noro_dwarf_vpec_sratio_hs_hr3_$(NSAMPLES).sav \
	--mcsample --nsamples=$(NSAMPLES) \
	--init=$(FAKEDIR)all_simpledrift-dehnen_noro_dwarf_vpec_sratio_hs_hr3.sav \
	--noro --dwarf --fitvpec --fitsratio --fiths

